name: Allowlist Token Manually

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: Network
        required: true
        options:
          - arc
          - robinhood
          - helios
          - irys
      tokenAddress:
        type: string
        description: Token Address
        required: true
      tokenSymbol:
        type: string
        description: Token Symbol
        required: false

jobs:
  allowlist-token:
    uses: ./.github/workflows/allowlist.yml
    secrets: inherit
    with:
      network: ${{ github.event.inputs.network }}
      tokenAddress: ${{ github.event.inputs.tokenAddress }}
      tokenSymbol: ${{ github.event.inputs.tokenSymbol }}
