name: Allowlist Token

on:
  workflow_call:
    inputs:
      network:
        type: string
        required: true
      tokenAddress:
        type: string
        required: true
      tokenSymbol:
        type: string
        required: false

jobs:
  allowlist-token:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx ts-node ./src/lib/scripts/allowlist-token.ts --network ${{ inputs.network }} --tokenAddress "${{ inputs.tokenAddress }}" --tokenSymbol "${{ inputs.tokenSymbol }}"

      - run: npm run generate
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          POKT_KEY: ${{ secrets.POKT_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Add ${{ inputs.tokenSymbol }} to ${{ inputs.network }} allowlist'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-allowlist-${{ inputs.network }}-${{ inputs.tokenAddress }}
          base: main
          delete-branch: true
          title: 'Allowlist ${{ inputs.tokenSymbol }} on ${{ inputs.network }}'
          body: |
            This PR was autogenerated by the Synthra token allowlist action.
          draft: false
          labels: allowlist
